@api=http://localhost:8080

POST {{api}}/todos
Content-Type: application/json

{
    "title":"lorem ipsum",
    "description":"lorem ipsum"
}
###
GET {{api}}/todos
###
DELETE {{api}}/todos/61ac04e8e581860cd81e44aa
###
PUT {{api}}/todos/61ac27a46e2bb590ab6c1ce4
Content-Type: application/json

{
    "title":"test ipsum",
    "description":"lorem ipsum"
}
###
GET {{api}}/todos/61ac27a46e2bb590ab6c1ce4