@api=http://localhost:8080

POST {{api}}/todos
Content-Type: application/json

{
    "title":"lorem ipsum",
    "description":"lorem ipsum"
}
###
GET {{api}}/todos


###
DELETE {{api}}/todos/61ac04e8e581860cd81e44aa