@api=http://localhost:8080
@credential=Bearer YOUR_TOKEN

POST {{api}}/signup
Content-Type: application/json

{
    "email":"test@gmail.com", 
    "password":"test", 
    "name":"test", 
    "username":"test avatar"
}
###
POST {{api}}/login
Content-Type: application/json

{
    "email":"test@gmail.com", 
    "password":"test"
}

###
GET  {{api}}/users
Content-Type: application/json
Authorization: {{credential}}

{
    "uid": "61ac3f050e14af25993186fb"
}
