@api=http://localhost:8080

POST {{api}}/signup
Content-Type: application/json

{
    "email":"test@gmail.com", 
    "password":"test", 
    "name":"test", 
    "username":"test avatar"
}
###
POST {{api}}/login
Content-Type: application/json

{
    "email":"test@gmail.com", 
    "password":"test"
}
